/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.practicum.explorewithme.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import ru.practicum.explorewithme.model.EndpointHit;

import javax.validation.Valid;

@Validated
public interface HitApi {

    @RequestMapping(value = "/hit",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<EndpointHit> hit(@Valid @RequestBody EndpointHit body);

}

