/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.practicum.explorewithme.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import ru.practicum.explorewithme.exceptions.notfound.CategoryNotFoundException;
import ru.practicum.explorewithme.model.category.CategoryDto;

import javax.validation.Valid;
import java.util.List;

@Validated
public interface CategoriesApi {

    @RequestMapping(value = "/categories",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<CategoryDto>> getCategories(@Valid @RequestParam(value = "from", required = false, defaultValue="0") Integer from,
                                                    @Valid @RequestParam(value = "size", required = false, defaultValue="10") Integer size);

    @RequestMapping(value = "/categories/{catId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CategoryDto> getCategoryById(@PathVariable("catId") Long catId) throws CategoryNotFoundException;
}

