/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package ru.practicum.explorewithme.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import ru.practicum.explorewithme.exceptions.notfound.CompilationNotFoundException;
import ru.practicum.explorewithme.model.compilation.CompilationDto;

import javax.validation.Valid;
import java.util.List;

@Validated
public interface CompilationsApi {

    @RequestMapping(value = "/compilations/{compId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<CompilationDto> getCompilationById(@PathVariable("compId") Long compId) throws CompilationNotFoundException;

    @RequestMapping(value = "/compilations",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<CompilationDto>> getCompilations(@Valid @RequestParam(value = "pinned", required = false) Boolean pinned,
                                                         @Valid @RequestParam(value = "from", required = false, defaultValue = "0") Integer from,
                                                         @Valid @RequestParam(value = "size", required = false, defaultValue = "10") Integer size);

}

