/*
 * Main service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CategoryDto;
import io.swagger.client.model.UserShortDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Краткая информация о событии
 */
@Schema(description = "Краткая информация о событии")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-09-19T14:44:37.459Z[GMT]")
public class EventShortDto {
  @SerializedName("annotation")
  private String annotation = null;

  @SerializedName("category")
  private CategoryDto category = null;

  @SerializedName("confirmedRequests")
  private Long confirmedRequests = null;

  @SerializedName("eventDate")
  private String eventDate = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("initiator")
  private UserShortDto initiator = null;

  @SerializedName("paid")
  private Boolean paid = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("views")
  private Long views = null;

  public EventShortDto annotation(String annotation) {
    this.annotation = annotation;
    return this;
  }

   /**
   * Краткое описание
   * @return annotation
  **/
  @Schema(example = "Эксклюзивность нашего шоу гарантирует привлечение максимальной зрительской аудитории", required = true, description = "Краткое описание")
  public String getAnnotation() {
    return annotation;
  }

  public void setAnnotation(String annotation) {
    this.annotation = annotation;
  }

  public EventShortDto category(CategoryDto category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @Schema(required = true, description = "")
  public CategoryDto getCategory() {
    return category;
  }

  public void setCategory(CategoryDto category) {
    this.category = category;
  }

  public EventShortDto confirmedRequests(Long confirmedRequests) {
    this.confirmedRequests = confirmedRequests;
    return this;
  }

   /**
   * Количество одобренных заявок на участие в данном событии
   * @return confirmedRequests
  **/
  @Schema(example = "5", description = "Количество одобренных заявок на участие в данном событии")
  public Long getConfirmedRequests() {
    return confirmedRequests;
  }

  public void setConfirmedRequests(Long confirmedRequests) {
    this.confirmedRequests = confirmedRequests;
  }

  public EventShortDto eventDate(String eventDate) {
    this.eventDate = eventDate;
    return this;
  }

   /**
   * Дата и время на которые намечено событие (в формате \&quot;yyyy-MM-dd HH:mm:ss\&quot;)
   * @return eventDate
  **/
  @Schema(example = "2024-12-31 15:10:05", required = true, description = "Дата и время на которые намечено событие (в формате \"yyyy-MM-dd HH:mm:ss\")")
  public String getEventDate() {
    return eventDate;
  }

  public void setEventDate(String eventDate) {
    this.eventDate = eventDate;
  }

  public EventShortDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Идентификатор
   * @return id
  **/
  @Schema(example = "1", description = "Идентификатор")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public EventShortDto initiator(UserShortDto initiator) {
    this.initiator = initiator;
    return this;
  }

   /**
   * Get initiator
   * @return initiator
  **/
  @Schema(required = true, description = "")
  public UserShortDto getInitiator() {
    return initiator;
  }

  public void setInitiator(UserShortDto initiator) {
    this.initiator = initiator;
  }

  public EventShortDto paid(Boolean paid) {
    this.paid = paid;
    return this;
  }

   /**
   * Нужно ли оплачивать участие
   * @return paid
  **/
  @Schema(example = "true", required = true, description = "Нужно ли оплачивать участие")
  public Boolean isPaid() {
    return paid;
  }

  public void setPaid(Boolean paid) {
    this.paid = paid;
  }

  public EventShortDto title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Заголовок
   * @return title
  **/
  @Schema(example = "Знаменитое шоу 'Летающая кукуруза'", required = true, description = "Заголовок")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public EventShortDto views(Long views) {
    this.views = views;
    return this;
  }

   /**
   * Количество просмотрев события
   * @return views
  **/
  @Schema(example = "999", description = "Количество просмотрев события")
  public Long getViews() {
    return views;
  }

  public void setViews(Long views) {
    this.views = views;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventShortDto eventShortDto = (EventShortDto) o;
    return Objects.equals(this.annotation, eventShortDto.annotation) &&
        Objects.equals(this.category, eventShortDto.category) &&
        Objects.equals(this.confirmedRequests, eventShortDto.confirmedRequests) &&
        Objects.equals(this.eventDate, eventShortDto.eventDate) &&
        Objects.equals(this.id, eventShortDto.id) &&
        Objects.equals(this.initiator, eventShortDto.initiator) &&
        Objects.equals(this.paid, eventShortDto.paid) &&
        Objects.equals(this.title, eventShortDto.title) &&
        Objects.equals(this.views, eventShortDto.views);
  }

  @Override
  public int hashCode() {
    return Objects.hash(annotation, category, confirmedRequests, eventDate, id, initiator, paid, title, views);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventShortDto {\n");
    
    sb.append("    annotation: ").append(toIndentedString(annotation)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    confirmedRequests: ").append(toIndentedString(confirmedRequests)).append("\n");
    sb.append("    eventDate: ").append(toIndentedString(eventDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    initiator: ").append(toIndentedString(initiator)).append("\n");
    sb.append("    paid: ").append(toIndentedString(paid)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    views: ").append(toIndentedString(views)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
